services:
  - type: web
    name: karma-kommand-kenter
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python server.py
    envVars:
      - key: RIOT_API_KEY
        sync: false
